### ISSUE TITLE
Error updateDB : package or namespace load failed

### ISSUE THREAD

**Issue by odethier-ulb** [h836472/ContScout#4]
Hello,

I have an issue while trying to install a database (uniref90) using a singularity image built from the latest docker image, it also appears with a simple <code>updateDB -i</code>.

Here are the commands I typed:

i. <code>singularity build contscout_latest.sif docker://h836472/contscout:latest</code> (downloaded and built this 05/21/2024)
ii. <code>singularity exec contscout_latest.sif updateDB -i</code>

And for the output I have:
<code>
During startup - Warning messages:
1: Setting LC_TIME failed, using "C"
2: Setting LC_MONETARY failed, using "C"
3: Setting LC_PAPER failed, using "C"
4: Setting LC_MEASUREMENT failed, using "C"
This is the database updater component of ContScout.
Loading R libraries.
Error: package or namespace load failed for ‘googlesheets4’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘glue’ 1.4.1 is already loaded, but >= 1.4.2 is required
Execution halted
</code>

Is it possible to update the docker image or provide a workaround to install a database?

Regards

**Comment by h836472** [comment]
Hi There,

This is a quick e-mail with an unconfirmed hint assuming you wish to
proceed with the troubleshooting fast. (I will have the chance to deal with
the request more thoroughly only by the end of the week)

I assume that Singularity mounts up your host /home directory where glue
1.4.1 is installed.  The bug is caused by your host "local" library version
overriding the one that is installed within the container.

You might wish to mount your singularity home manually, to an external
empty folder, away from your host R libraries
singularity -B /my_empty_directory:/home exec contscout_latest.sif updateDB
-i

Also, please do not forget to mount a write-able temp folder too, when
starting singularity

Hope the hint fits and solves your issue. Please let me know if it helps
and then I add a description to the portal too, so that this error will be
covered for all users.

Balazs

**Comment by odethier-ulb** [comment]
Thank you, indeed by mounting a new home it seems to be running now.
