### ISSUE TITLE
Issue with binary Docker Image, using the run example

### ISSUE THREAD

**Issue by j-hinton02** [h836472/ContScout#6]
I am attempting to use ContScout for a research project I am working on. I am using it through the binary Docker image, installed using the method provided in the manual. 

I was going through the run example in the manual in order to get started but when I run the updateDB -u ~/test/database 
-d swissprot command. I get an error

Here is the command:
$ docker run h836472/contscout:latest updateDB -u ~/test/database -d swissprot 

Output:
This is the database updater component of ContScout.
Loading R libraries.
Downloading database URL file
✔ Reading from "ContScoutDatabases".
✔ Range 'Sheet1'.
Using 16 CPUs for general tasks and 8 CPUs for IO operations.
Directory /home/joseph/test/database,could not be created. Please check available space and user premissions.
Warning message:
In dir.create(x) :
  cannot create dir '/home/joseph/test/database', reason 'No such file or directory'

The directory does exist and I have tried deleting it and remaking it to make sure.

I am running this in Ubuntu version 24.04 and with docker engine version 25.0.2

**Comment by h836472** [comment]
You are encountering a folder access issue that is a direct result of containerization. Your real-world (host) home folder from machine can not be accessed by the Docker container because it is not mounted to the virtual environment by default. 
Here is, what you can do in docker: using the -v host:guest mounting formula, you can point to an external directory on your host and make it available in the guest under the path of your choice. 

Example: 
_docker run _**-v /home/MyName/test/database:/dockerDB**_ -u /dockerDB -d swissprot_

Please notice how the internal directory path in the right part of the -v tag matches the  path passed to -u parameter of ContScout. 

A quick side note here: your example works flawlessly in Singularity, because it does attach the home directory by default. That feature from Singularity is convenient in many cases but at the same time it can cause weird library clashes when user-installed packages in the home directory can "sneak in" into the guest environment and can cause compatibility problem. 
While skipping the auto-mount of home directory by Docker means that you need to explicitly mount every external folder you wish to use, that gives you perfect control over which files are visible from host to guest. Thus, library clash "accidents" between host and guest that might happen in Singularity won't ever happen in the more strict Docker environment.

**Comment by j-hinton02** [comment]
This is exactly what I needed to know. Thank you so much!
